### PR TITLE
Update appveyor and README for vs2015.

### PR DESCRIPTION
**Pull request by chrisdembia**
Let's see if this works!

### CODE REVIEW

**Comment by chrisdembia** [comment]
*whew* tests pass.

**Comment by sherm1** [comment]
Perfect! Thanks, Chris. I'll merge this in the morning so things won't break overnight.

**Comment by chrisdembia** [comment]
Okay just as a reminder, that means subsequent OpenSim's build will start failing.

**Comment by sherm1** [comment]
Merging now. This removes the restriction on Simbody master branch to remain compatible with VS2013. OpenSim PR opensim-org/opensim-core#577 should be modified to make the same change and merged as soon as possible.

**Pull request merged**
