### PR TITLE
[appveyor] Upgrade from Visual Studio 2015 to 2017.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR updates the AppVeyor file to build Simbody with Visual Studio 2017.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/616)

### CODE REVIEW

**Comment by chrisdembia** [comment]
@sherm1 This PR changes the AppVeyor build to build Simbody with Visual Studio 14 2015 and Visual Studio 15 2017, instead of in in 32-bit and 64-bit. The reasoning is that OpenSim 4.0 will not have a 32-bit release, and we would like to move to Visual Studio 15 2017.

**Comment by chrisdembia** [comment]
Ready for review.

I cancelled the Travis-CI builds manually, because the Travis CI builds are unaffected.

**Comment by sherm1** [comment]
:lgtm: -- I have no interest in 32 bit Simbody! Let them eat 64 bits.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/616#-:-L4J5JKuEQNF7jzI_sWO:bhej2k5)*

**Comment by chrisdembia** [comment]
🍰 

Okay thanks; merging.

**Pull request merged**
