### PR TITLE
Remove check of reference against nullptr.

### LINKED ISSUE #388: clang 3.6 gives "Undefined bool conversion" in ClonePtr
```
/Users/chris/repos/simbody/1/install/include/simbody/SimTKcommon/internal/ClonePtr.h:84:16
: warning: 
      reference cannot be bound to dereferenced null pointer in well-defined C++
      code; pointer may be assumed to always convert to true
      [-Wundefined-bool-conversion]
    {   reset(&t ? t.clone()  :0); return *this; }
```

http://stackoverflow.com/questions/28689269/how-to-fix-reference-cannot-be-bound-to-dereferenced-null-pointer-warning

Any ideas on how to fix this?

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes #388.

### CODE REVIEW

**Comment by sherm1** [comment]
I see that I took a different approach in Simbody 4.0 for `CloneOnWritePtr`. I created a little helper routine:
```
    // If src is non-null, clone it; otherwise return null.
    static T* cloneOrNull(const T* src) {
        return src ? src->clone() : nullptr;
    }
```
When given a `const T& t`, this is used like this: `reset(cloneOrNull(&t))`. I didn't do that to avoid the warning but to avoid the many duplicate `?:` tests -- pointers p use `cloneOrNull(p)`. I suspect that would slip by clang 3.6 silently and would still guard against null references.

Please feel free to merge it as-is but if so please add a note to issue #328 to mention that ClonePtr & CloneOnWritePtr should be made to match wrt cloneOrNull() eventually.

**Comment by chrisdembia** [comment]
I'm not sure I understand the reason for giving the user a nullptr instead of causing the segfault. Is it so they can check if they can have logic that tests for the nullptr?

**Comment by sherm1** [comment]
No, it would only be to help out bozos who went to the trouble to create an illegal null reference object. I think it would be better *not* to check the references for null, that is, the way you fixed it. But it would also be better to use cloneOrNull() rather than a bunch of repeated code for the pointers, where it is legitimate to expect nulls. The point of issue #328 is that the two pointer implementations ought to be almost identical.

**Comment by chrisdembia** [comment]
So it sounds like what we should do is, for methods taking references, just go ahead and clone (in both pointer classes), and for methods taking pointers, use `cloneOrNull()`? I can try this.

**Comment by sherm1** [comment]
Yeah, that seems like the best approach. I'm slightly torn because I know people do occasionally create null references but we probably shouldn't encourage the practice by hiding the consequences.

**Comment by sherm1** [comment]
I'm going to have to rework ClonePtr soon anyway to bring it into C++11 compliance, so if you want to leave it with just the existing fix that's fine.

**Comment by chrisdembia** [comment]
> I'm slightly torn because I know people do occasionally create null references but we probably shouldn't encourage the practice by hiding the consequences.

You have the benefit/curse of experience, while I have the benefit/curse of naive idealism.

**Comment by chrisdembia** [comment]
I tried to improve consistency within ClonePtr by adding a cloneOrNull(), but I do not plan on making similar changes to CloneOnWritePtr.

**Comment by sherm1** [comment]
Thanks -- perfect.

**Pull request merged**
