### PR TITLE
ADOLC SmallMatrix Random PolygonalMesh

### PR DESCRIPTION
**Pull request by antoinefalisse**
@sherm1 @chrisdembia : This PR contains minor changes in `SmallMatrix.cpp`, `Random.cpp`, and `PolygonalMesh.cpp` necessary to build Simbody with ADOLC. The changes mainly consisted in replacing `std::` by `Ntraits<Real>::` so that statements are valid with `adouble` too. I don't know if tests are necessary for this PR but, if so, please let me know what you would like to see tested. This PR is based on #618 still in review. Thanks in advance.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/620)

### CODE REVIEW

**Comment by chrisdembia** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SimTKcommon/Random/src/Random.cpp, line 28 at r1](https://reviewable.io:443/reviews/simbody/simbody/620#-L5kGTOuMG0z8S46zmEd:-L5kGTOuMG0z8S46zmEe:bm2im3b) ([raw file](https://github.com/simbody/simbody/blob/b433af8f6370558cbf502ae6f885cf063096d60f/SimTKcommon/Random/src/Random.cpp#L28)):*
> ```cpp
> #include "SimTKcommon/internal/Random.h"
> #include "SimTKcommon/internal/AtomicInteger.h"
> #include <SimTKcommon/internal/NTraits.h>
> ```

Can you use `#include "SimTKcommon/internal/NTraits.h"` for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/620)*

**Comment by antoinefalisse** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[SimTKcommon/Random/src/Random.cpp, line 28 at r1](https://reviewable.io:443/reviews/simbody/simbody/620#-L5kGTOuMG0z8S46zmEd:-L5kIWTWhuY3i2UzjvPN:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/b433af8f6370558cbf502ae6f885cf063096d60f/SimTKcommon/Random/src/Random.cpp#L28)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Can you use `#include "SimTKcommon/internal/NTraits.h"` for consistency?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/620)*

**Comment by sherm1** [comment]
#618 is ready to merge now -- then this one should trim down substantially (and be easier to review). You may want to rebase this branch after you merge #618.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/620#-:-L7MiWJ0T10-8IrQxnsL:b-h3qmh7)*

**Comment by antoinefalisse** [comment]
@sherm1, #618 is merged so it is ready for your review. It already got a lgtm from @chrisdembia.

**Comment by chrisdembia** [comment]
@sherm1 if you get some time soon, this PR is ready for review.

**Comment by sherm1** [comment]
Sorry for the delay -- :lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/simbody/simbody/620#-:-L8PfocJ879h5wULjcWZ:b-b0u7j3)*

**Pull request merged**
