### PR TITLE
Migrate sprintf() to snprintf()

### PR DESCRIPTION
**Pull request by fcanderson**
Mac builds are failing due to the use of sprintf(), which has been deprecated.

In this PR, instances of sprintf() are replaced by snprintf().  Likewise, instances of vsprintf() are replaced by vsnprintf().

In some files, trailing whitespace is also removed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/760)

### CODE REVIEW

**Comment by fcanderson** [comment]
@sherm1
The Mac build is passing, so the changes are ready for a review.  There were a few instances that needed some extra care not to step on existing variable names.  Those instances, which I think will be obvious because I used a more complex name for the ```const int``` used to set the size of a buffer array, could especially use a second look.

**Comment by fcanderson** [comment]
I just realized that Reviewable does a good enough job of filtering out the lines with only whitespace changes that my efforts to make my sprintf() changes easier to find were likely for naught.  I am however relieved that the task of reviewing my changes won't be quite as tedious and onerous as I first thought.

**Review by sherm1 — APPROVED** [review]
Awesome! :lgtm_strong: Thanks so much for doing this, Clay.

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/simbody/simbody/760#-:-Nd6oM8F6lgno9HaAnBp:bamhfq8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fcanderson)

**Comment by sherm1** [comment]
Mac build still failed after merge -- looks like Exception.h still has some stragglers: https://github.com/simbody/simbody/actions/runs/6006381806/job/16290815340

Want to knock those out too?

**Comment by fcanderson** [comment]
Yep. Wonder why Exception.h passed for me? Anyway, I'll take care of the stragglers!
I also found a tweak that should be made in IpOptionList.cpp. (or something close to that file name)

**Comment by fcanderson** [comment]
I checked my version of ```Exception.h```.  I didn't find any stragglers.  And, the PR diff shows that the ```sprintf()```s were changed.  So, something wonky is going on.

The ```sprintf()``` errors are being generated during the processing of ```ExceptionMacros.h```.  Could it be that ```ExceptionMacros.h```, which includes ```Exception.h```, is somehow pulling in an old ```Exception.h``` from somewhere?  Is ```ExceptionMacros.h``` pulling from an include path that hasn't yet received the updated ```Exception.h``` file?

**Comment by fcanderson** [comment]
I just checked Simbody:master. There are no ```sprintf()```s in Exception.h.
Is the Mac build failing on a branch that hasn't yet been sync'ed with Simbody:master?

**Comment by fcanderson** [comment]
Ok.  I figured it (I think).  The run that you linked was before the merge of this PR (#760).

The run you linked was for #759, which corrected the ```sprintf()```s in String.h but in no other files.  The title of #759 is similar to #760.

The build for #760 will pass on the Mac I think.

**Comment by sherm1** [comment]
Ah, great -- sorry for the confusion!

**Pull request merged**
