### PR TITLE
Exponential springs now inherit from SimTK::Force

### PR DESCRIPTION
**Pull request by fcanderson**
@sherm1 

To more easily incorporate the ExponentialSpringForce contact model into OpenSim, I changed ExponentialSpringForce from being its own ForceSubsystem (i.e., inheriting from SimTK::ForceSubsystem) to inheriting from SimTK::Force.

This rework required one code change outside of ExponentialSpringForceImpl.  Namely, instead of taking a MultibodySystem as an argument to its constructor, ExponentialSpringForce now takes a GeneralForceSubsystem.  This one code change was then accompanied by the corresponding change to the Doxygen comments for the constructor.

Within ExponentialSpringForceImpl, more changes were required, but they were fairly systematic:
- Instead of being able to call many ForceSubsystem methods directly, those methods had to be called on the GeneralForceSubsystem.  So, throughout the code, you will see calls to SimTK::ForceImpl::getForceSubsystem() which returns the GeneralForceSubsystem.
- The standard SimTK_INSERT_DERIVED_HANDLE_DEFINITIONS are used instead of having explicit versions of getImpl() and updImpl().
- realizeSubsystemDynamicsImpl() was replaced by a call to calcForce().  The calcForce() method, along with calcNormalForce() and calcFrictionForce(), were positioned in the ExponentialSpringForce.cpp file to directly precede calcPotentialEnergy(), as opposed to falling in the midst of the other realize methods.

Because I re-proofed the documentation, I took the opportunity to correct a few minor documentation errors that I found and tweak a few comments.

All tests (TestExponentialSpring.cpp) are passing.  I also verified that the Test_Adhod - ExponentialSpringsComparison is running as expected.

I hope this PR doesn't cause a headache.  I'm sorry that I wasn't a little more savvy when undertaking the original development of this contact class.  It would have been good starting off knowing what would be easiest to incorporate into OpenSim.

Frankly, until I have fully incorporated ExponentialSpringForce into OpenSim, it would probably be wise to expect more changes to ExponentialSpringForce.  For that reason, it may be a good idea to wait to merge this PR until Exponential Springs are fully up and running in OpenSim 4.4.   I thought it would be good for folks more experienced than I to have the option to merge earlier (rather than later), so I went ahead and submitted the PR.

Thanks,
Clay

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/734)

### CODE REVIEW

**Comment by aymanhab** [comment]
@fcanderson Thanks for working on this, getting Simbody side in is as easy as updating the commit hash at some point over the next couple weeks so no pressure. For OpenSim side we'd love to document, test with various other tools, GUI, scripting and eventually publicize so it will take some time anyway.

**Review by fcanderson — COMMENTED** [review]
Ok. Thanks for the info Ayman. Extensive documentation and testing in OpenSim will be good! I look forward to helping out with that.

The documentation on the Simbody side, especially after Sherm's comments, I think is particularly good.  So, it would be good to find a way to make use of that documentation on the OpenSim side that doesn't involve duplicating the Doxygen comments. 

> *[Reviewable](https://reviewable.io/reviews/simbody/simbody/734#-:-N2CncTb04VqvPz-V8FT:bcnefdn)* status: 0 of 7 files reviewed, all discussions resolved

**Review by fcanderson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/simbody/simbody/734)* status: 0 of 7 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/simbody/simbody/734#-N2Cppbp8yzAYoRLPJXd:-N2CppbqBh8EA7aJmgpi:b-y14rg7) (no related file):*
To find the changes since the last merge efficiently, I suggest doing the following:

In `ExponentialSpringForce.h`,
1. Check the include files at the top of the file.
2. Check the class and constructor declarations.  Formerly, the `ExponentialSpringForce` class inherited from `ForceSubsystem`; it now inherits from `Force`.  Formerly, the constructor took a `MultibodySystem`; it now takes a `GeneralForceSubsystem`.
3. Search on `SimTK_INSERT_DERIVED_HANDLE_DECLARATIONS`

In `ExponentialSpringForce.cpp`,
1. Check the include files at the top of the file.
2. Search on `ForceImpl`, matching the WHOLE WORD, to find the places where return values and method signatures changed.
3. Search on `getForceSubsystem().` to find all the calls that now need to be made via the `GeneralForceSubsystem` instead of the former parent `ForceSubsystem`.
4. Search on `calcForce()` and check the contents of that method.

Note that I moved some methods around within `ExponentialSpringForce.cpp`, and, as a result, GitHub (and Reviewable) have kind of butchered some of the diffs.  For the `realize` methods and `calcForce()`, it will be easier to look at the source code instead of the GitHub or Reviewable diffs.

No changes, other than documentation tweaks, were made in `ExponentialSpringParameters.h` or in `ExponentialSpringParameters.cpp`.

The only change in `TestExponentialSpring.cpp` and `ExponentialSpringComparison.cpp` that were made were constructor calls to `ExponentialSpringForce`.  There, the `system` (`MultibodySystem`) was changed to `forces` (`GeneralForceSubsystem`).

I made minor changes to some of the documentation, but I am very confident that I changed what needed to be change (just the argument change in the constructor) and didn't introduce more errors than I corrected.  So, I would not spend any time on the documentation.

___

**Review by sherm1 — APPROVED** [review]
This looks good, Clay -- I found a few typos.

Style suggestion: the many new calls to getForceSubsystem() add unnecessary clutter. You could eliminate most of them by adding a few one-line private helper methods, e.g. `getStage(state) { return getForceSubsystem().getStage(state); }` I would suggest doing that for any of the subsystem-level methods that get used repeatedly throughout the code.

:lgtm:

> Reviewed 1 of 7 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/simbody/simbody/734#-:-N3LO9qr2e_RLfKjKXXo:bhcszbw)* status: all files reviewed, 4 unresolved discussions (waiting on @fcanderson)

___
*[`Simbody/include/simbody/internal/ExponentialSpringForce.h` line 467 at r4](https://reviewable.io/reviews/simbody/simbody/734#-N3LKcW55amJNIUMMmDQ:-N3LKcW55amJNIUMMmDR:bt7qmyw) ([raw file](https://github.com/simbody/simbody/blob/9dbbb67949cf7f23fb9de42e8d4767c610f2ca06/Simbody/include/simbody/internal/ExponentialSpringForce.h#L467)):*
> ```objc
>     Real getSliding(const State& state) const;
> 
>     /** Reset the friciton spring zero (elastic anchor point) so that it
> ```

typo: friciton -> friction
___
*[`Simbody/src/ExponentialSpringForce.cpp` line 381 at r4](https://reviewable.io/reviews/simbody/simbody/734#-N3LM7PbCKwWYislKhdi:-N3LM7Pc1R-RocnJtRLK:b-n6etyj) ([raw file](https://github.com/simbody/simbody/blob/9dbbb67949cf7f23fb9de42e8d4767c610f2ca06/Simbody/src/ExponentialSpringForce.cpp#L381)):*
> ```cpp
> //------------------------------
> // Note that "realizeDynamics()" is replaced by "calcForce()". See below.
> //------------------------------
> ```

nit: this comment should be removed before this gets merged
___
*[`Simbody/src/ExponentialSpringForce.cpp` line 389 at r4](https://reviewable.io/reviews/simbody/simbody/734#-N3LMMIQ70w2jlYM2xMg:-N3LMMIQ70w2jlYM2xMh:b-mb1osc) ([raw file](https://github.com/simbody/simbody/blob/9dbbb67949cf7f23fb9de42e8d4767c610f2ca06/Simbody/src/ExponentialSpringForce.cpp#L389)):*
> ```cpp
> // Two states are managed at this Stage: Sliding amd SlidingAction.
> //
> // Sliding is a continuous state (a "Z" in Simbody vocabuary), and its time
> ```

typo: vocabuary -> vocabulary

**Review by fcanderson — COMMENTED** [review]
Thanks for the review Sherm.  I corrected the typos and followed up on your style suggestion.  Private pass-though methods are now used to eliminate almost all calls to getForceSubsystem() from the main code.

The PR is ready to be merged.

LGTM

> *[Reviewable](https://reviewable.io/reviews/simbody/simbody/734#-:-N3WOcUH1NIAOWif91E7:b-s5pc0t)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @fcanderson and @sherm1)

___
*[`Simbody/include/simbody/internal/ExponentialSpringForce.h` line 467 at r4](https://reviewable.io/reviews/simbody/simbody/734#-N3LKcW55amJNIUMMmDQ:-N3T_drv1O2hidubp2Ok:bb6un1j) ([raw file](https://github.com/simbody/simbody/blob/9dbbb67949cf7f23fb9de42e8d4767c610f2ca06/Simbody/include/simbody/internal/ExponentialSpringForce.h#L467)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: friciton -> friction
</blockquote></details>

Done
___
*[`Simbody/src/ExponentialSpringForce.cpp` line 381 at r4](https://reviewable.io/reviews/simbody/simbody/734#-N3LM7PbCKwWYislKhdi:-N3TZopL7SUq0zCbc10W:bb6un1j) ([raw file](https://github.com/simbody/simbody/blob/9dbbb67949cf7f23fb9de42e8d4767c610f2ca06/Simbody/src/ExponentialSpringForce.cpp#L381)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: this comment should be removed before this gets merged
</blockquote></details>

Done
___
*[`Simbody/src/ExponentialSpringForce.cpp` line 389 at r4](https://reviewable.io/reviews/simbody/simbody/734#-N3LMMIQ70w2jlYM2xMg:-N3T_37O1pM3jyEV_L1Q:bb6un1j) ([raw file](https://github.com/simbody/simbody/blob/9dbbb67949cf7f23fb9de42e8d4767c610f2ca06/Simbody/src/ExponentialSpringForce.cpp#L389)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

typo: vocabuary -> vocabulary
</blockquote></details>

Done

**Comment by aymanhab** [comment]
Merging based on earlier comments/review, thanks @fcanderson

**Pull request merged**
