### PR TITLE
ADOLC Common

### PR DESCRIPTION
**Pull request by antoinefalisse**
+@sherm1, +@chrisdembia. This PR contains the changes in `common.h` that will enable setting`Real `as `adouble` when building Simbody with ADOLC. However, for now, `Real `is still set to `double ` so that we can build Simbody with ADOLC in CI and have tests. There are a couple of additional minor changes in `common.h`. This PR also contains some changes in the CMake files that were needed to copy the ADOLC dll that is needed in tests relying on ADOLC drivers. `simbody_cmake_macros` has been directly copied from one of @chrisdembia's projects.  Finally, this PR contains a simple test case that does some trivial use of `adouble `, ie it computes the derivative of a simple function. Please let me know if you would like to see other tests in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/600)

### CODE REVIEW

**Comment by chrisdembia** [comment]
The Linux builds are failing because the Linux filesystem is case-sensitive: 

```
CMake Error at CMakeLists.txt:45 (include):
  include could not find load file:
    cmake/simbody_macros.cmake
```

Consider naming the file either `SimbodyMacros.cmake` or `simbody_macros.cmake`.

**Comment by chrisdembia** [comment]
@antoinefalisse I have a few relatively minor comments. Great start! It's definitely easier to review a small PR like this.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[cmake/Simbody_macros.cmake, line 34 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0muLdO_vfjgB2rS4Xj:-L0muLdPmHvGjRncj6GM:bcw6e2q) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/cmake/Simbody_macros.cmake#L34)):*
> ```CMake
>         add_custom_target(Copy_${DEP_NAME}_DLLs ALL DEPENDS ${DLLS_DEST})
>         set_target_properties(Copy_${DEP_NAME}_DLLs PROPERTIES
>             PROJECT_LABEL "Copy ${DEP_NAME} DLLs" FOLDER "simbody")
> ```

You can remove `FOLDER "simbody"`; Simbody does not use CMake's FOLDERs (this affects the organization of the Solution Explorer in Visual Studio).

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 26 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvdtxAsw25A6t4ysq:-L0mvdtxAsw25A6t4ysr:bxeo6dt) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L26)):*
> ```cpp
> #include "SimTKcommon.h"
> #include "SimTKcommon/Testing.h"
> #include <adolc\adolc.h>
> ```

This should be `<adolc/adolc.h>` for this to work cross-platform.

Could you add a comment above saying that `adolc.h` is included to access the `jacobian()` driver?

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 35 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvyGm73a9F1VYIhMg:-L0mvyGm73a9F1VYIhMh:b-io40t3) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L35)):*
> ```cpp
> using namespace SimTK;
> 
> // Test derivative of simple function with ADOLC
> ```

You might also say "without Simbody; just to make sure ADOLC is included properly."

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 42 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvHkhx7RPbYYQuPFn:-L0mvHkiQxAmiWX_XtzL:b2kip6l) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L42)):*
> ```cpp
>     trace_on(1);
>     adouble* x = new adouble[1];
>     adouble* y = new adouble[1];
> ```

`x` and `y` do not need to be vectors.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 52 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvVX8VVgGAd7yx6Iv:-L0mvVX8VVgGAd7yx6Iw:b5zvcbg) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L52)):*
> ```cpp
>     J = myalloc(1,1);
>     jacobian(1, 1, 1, xp, J);
>     SimTK_TEST(J[0][0] == 48.355705212176716);
> ```

Consider using `9 * pow(x[0], 2) - sin(x[0])` here instead.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 53 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvRMnviLzqwKMHI2h:-L0mvRMnviLzqwKMHI2i:bdwndww) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L53)):*
> ```cpp
>     jacobian(1, 1, 1, xp, J);
>     SimTK_TEST(J[0][0] == 48.355705212176716);
> ```

You should use `myfree(J)` here (I think that's the name of the function).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L0mw7V_lyv2WhZZLCN6:bh7n7w1)*

**Comment by antoinefalisse** [comment]
@chrisdembia, thanks for the review. The latest commit contains the required changes.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 26 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvdtxAsw25A6t4ysq:-L0nBAeYFQ8wdyDacgd-:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L26)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

This should be `<adolc/adolc.h>` for this to work cross-platform.

Could you add a comment above saying that `adolc.h` is included to access the `jacobian()` driver?
</blockquote></details>

Done.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 35 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvyGm73a9F1VYIhMg:-L0nBQrXNbLd3jQ4ZCcP:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L35)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

You might also say "without Simbody; just to make sure ADOLC is included properly."
</blockquote></details>

Done.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 42 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvHkhx7RPbYYQuPFn:-L0nD-CehK-urBBcnPWW:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L42)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

`x` and `y` do not need to be vectors.
</blockquote></details>

Done.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 52 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvVX8VVgGAd7yx6Iv:-L0nD4ZqpnUkgy81rURe:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L52)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Consider using `9 * pow(x[0], 2) - sin(x[0])` here instead.
</blockquote></details>

Done.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 53 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvRMnviLzqwKMHI2h:-L0nD6lfBrzriZLLDNLS:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L53)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

You should use `myfree(J)` here (I think that's the name of the function).
</blockquote></details>

Done.

---

*[cmake/Simbody_macros.cmake, line 34 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0muLdO_vfjgB2rS4Xj:-L0nBElZl46b5APIZTAH:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/cmake/Simbody_macros.cmake#L34)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

You can remove `FOLDER "simbody"`; Simbody does not use CMake's FOLDERs (this affects the organization of the Solution Explorer in Visual Studio).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L0nNpMBAowgdyUVBDWg:b-si88v0)*

**Comment by chrisdembia** [comment]
Thanks for the quick changes. I have two more small comments.

---

Reviewed 5 of 6 files at r1, 3 of 4 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 42 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvHkhx7RPbYYQuPFn:-L0oxpfkmLyvyQIqr9MG:bnrgbi0) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L42)):*
<details><summary><i>Previously, antoinefalisse wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry to be a pain but these also do not need to be dynamically allocated. You should be able to use `adouble x;` (and remove `delete x;`).

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 53 at r2](https://reviewable.io:443/reviews/simbody/simbody/600#-L0oxlylXjKYX5nmuTpi:-L0oxlylXjKYX5nmuTpj:b1eobb2) ([raw file](https://github.com/simbody/simbody/blob/e0fb9e6cf1529321cda3e1c4ae5be28a8452d15f/SimTKcommon/tests/TestADOLCCommon.cpp#L53)):*
> ```cpp
>     J = myalloc(1,1);
>     jacobian(1, 1, 1, xp, J);
>     SimTK_TEST(J[0][0] == 9*pow(x[0],2)-sin(x[0]));
> ```

BTW It's so neat that this is *exact*!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L0oy1fgfjUeUGSItMzQ:bnd9j5)*

**Comment by chrisdembia** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600)*

**Comment by antoinefalisse** [comment]
Thanks, I made the changes.

---

Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 42 at r1](https://reviewable.io:443/reviews/simbody/simbody/600#-L0mvHkhx7RPbYYQuPFn:-L0rtB78L1X3UU5lVfaH:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/5ea2ecb8c70cca07b72274e7e628292be7224f82/SimTKcommon/tests/TestADOLCCommon.cpp#L42)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Sorry to be a pain but these also do not need to be dynamically allocated. You should be able to use `adouble x;` (and remove `delete x;`).
</blockquote></details>

Done.

---

*[SimTKcommon/tests/TestADOLCCommon.cpp, line 53 at r2](https://reviewable.io:443/reviews/simbody/simbody/600#-L0oxlylXjKYX5nmuTpi:-L0s37m9wn1ke2iBDYcL:bb77uci) ([raw file](https://github.com/simbody/simbody/blob/e0fb9e6cf1529321cda3e1c4ae5be28a8452d15f/SimTKcommon/tests/TestADOLCCommon.cpp#L53)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

BTW It's so neat that this is *exact*!
</blockquote></details>

Yep!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L0rtPrxUwP3tt44T0z6:b-r50er8)*

**Comment by chrisdembia** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L0v1XZ244RauXocu_wO:bnfp4nl)*

**Comment by antoinefalisse** [comment]
@sherm1, this PR is ready for review. Sorry if it is already on your list, just to be sure.

**Comment by sherm1** [comment]
+@sherm1 
This is great, @antoinefalisse -- thanks. Very easy to review when there is just one thing happening in a PR! Looking foward to more. :lgtm:

---

Reviewed 2 of 6 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[SimTKcommon/include/SimTKcommon/internal/common.h, line 123 at r3](https://reviewable.io:443/reviews/simbody/simbody/600#-L2HSYFtQu6Y0NjShTGf:-L2HSYFtQu6Y0NjShTGg:b-e9jnda) ([raw file](https://github.com/simbody/simbody/blob/56813b7c217686a18828a3676b75e1eaedbd89ac/SimTKcommon/include/SimTKcommon/internal/common.h#L123)):*
> ```objc
>             // Ignore warnings from ADOL-C headers.
>             #pragma warning(push)
>             // 'argument': conversion from 'size_t' to 'locint', possible loss of data.
> ```

BTW line length (keep to 80 chars, please)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L2HTbxPCcuihGEAU0eP:b31xfnx)*

**Comment by sherm1** [comment]
(This is ready to merge after one line length fix.)

**Comment by antoinefalisse** [comment]
@sherm1, thanks for the review. I fixed the line length and changed the included adolc header based on the comment in the other PR.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[SimTKcommon/include/SimTKcommon/internal/common.h, line 123 at r3](https://reviewable.io:443/reviews/simbody/simbody/600#-L2HSYFtQu6Y0NjShTGf:-L2LhqYmE17aGQIi0mxt:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/56813b7c217686a18828a3676b75e1eaedbd89ac/SimTKcommon/include/SimTKcommon/internal/common.h#L123)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW line length (keep to 80 chars, please)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L2Lhrnpp8ajQBtQ7fbS:brvdc32)*

**Comment by chrisdembia** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600#-:-L2LzNjfqyc_rEPAWA91:bnfp4nl)*

**Comment by chrisdembia** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/600)*

**Pull request merged**
