### PR TITLE
Update master to 3.8.

### LINKED ISSUE #679: Release Simbody 3.7
@sherm1 can I prepare a Simbody 3.6.2 release that includes the macOS Catalina fix (#676)?

- [x] update changelog
- [x] in README.md, replace "3.6" with "3.7"
- [x] check that README.md is up to date
- [x] update version number for user guide and advanced programming guide 
- [x] check theory manual
- [x] post doxygen on a new simbody repository (simbody-<version>-doxygen)
- [x] update release date of 3.7 in the changelog.
- [x] make 3.7 branch
- [x] make 3.7 release (tag)
- [ ] update master branch to 3.8
  - [x] add "3.8" section to CHANGELOG.md.
- [x] update github.com/simbody/simbody.github.io/index.html and github.com/simbody/simbody.github.io/latest/index.html.
- [x] announce release on forum

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR updates the master branch to version 3.8.

I also updated the CONTRIBUTING.md file (syntax error and mentioning Gil Serrancoli).

Fixes #679 .

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/681)

### CODE REVIEW

**Comment by chrisdembia** [comment]
@yurivict We typically put the names of contributors in our CONTRIBUTING.md file, but I do not know your full name. If you'd like to be credited in this way, then let us know your full name. Otherwise, we will use your GitHub handle. 

Thanks again for your contributions.

**Comment by yurivict** [comment]
My full name is Yuri Victorovich.

**Comment by chrisdembia** [comment]
Thanks; I updated our contributor list.

**Comment by sherm1** [comment]
Thanks -- merged.

**Pull request merged**
