### PR TITLE
Remove old TODO about std::thread

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR removes an outdated TODO.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/617)

### CODE REVIEW

**Comment by sherm1** [comment]
Yay! :lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/617#-:-L4NmoCm3aEGvy1dJQ4E:b21tl89)*

**Comment by chrisdembia** [comment]
Thanks @sherm1. Can I merge this? In general, can I merge my PRs after you've LGTM'd them?

**Comment by sherm1** [comment]
Yes and yes.

**Comment by chrisdembia** [comment]
Thanks.

**Pull request merged**
