### PR TITLE
ADOLC Row SymMat

### PR DESCRIPTION
**Pull request by antoinefalisse**
@sherm1, @chrisdembia, this PR contains the changes in `Row.h` and `SymMat.h` necessary to build Simbody with ADOL-C. This PR also contains various tests in `TestADOLCCommon.cpp` verifying that it works properly. This PR is very similar to #614 already merged. Once merged, all headers of SimTKcommon/SmallMatrix will be working with ADOL-C. Another PR (#626) is currently pending but does not need to be merged before this one is merged.

One remark, the following operations are not supported:

- a/r where a is an `adouble `and r a `Row`
- a-r where a is an `adouble `and r a `Row`
- a/sm where a is an `adouble `and sm a `SymMat`
- a-sm where a is an `adouble `and  sm a `SymMat`

but this is I think expected based on the discussion we already had for `Vec `and `Mat`.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/627)

### CODE REVIEW

**Comment by sherm1** [comment]
Please merge or rebase after #618 merges and poke me for a review.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/627#-:-L7Mitt8QWItSRCcHKpx:boq1ttn)*

**Comment by antoinefalisse** [comment]
@sherm1, #618 is merged so it is ready for your review. It already got a lgtm from @chrisdembia.

**Comment by antoinefalisse** [comment]
@sherm1, if you get a chance, this PR is ready for review too. Thanks.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/627#-:-L8TNRJhp7FxOtiLGlu4:bnfp4nl)*

**Comment by antoinefalisse** [comment]
Thanks

**Comment by chrisdembia** [comment]
🎆

**Pull request merged**
