### PR TITLE
Change Ipopt namespace to SimTKIpopt

### LINKED ISSUE #510: simbody includes and links statically a forked IpOpt library, whose symbols conflicts with system IpOpt
- Debian bug report : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830506
- Gazebo bug report : https://bitbucket.org/osrf/gazebo/issues/2005/segfault-when-calling-ipopt-virtual-method

Quoting @drdanz from the Debian bug report : 

> Simbody includes and links statically its private version of the ipopt library
> in libSimTKmath.so exports its symbols.
> 
> This causes issues when trying to link Ipopt and libSimTKmath in the same
> executable or when an executable linked to libSimTKmath opens a plugin linked
> to Ipopt (this happens for example when opening a plugin linked to Ipopt from
> gazebo).

As I am able to understand from https://github.com/simbody/simbody/issues/348 , the simbody internal IpOpt is a fork of an old version of IpOpt, so using directly the system version in simbody is not a viable alternative.
In that case I guess not exporting the IpOpt symbols anymore (or exporting them as different symbols, for example by wrapping them in a different namespace) is the best solution, but I guess that that is technically a change of ABI, even if it is impossible for a 3rd party project to use those symbols as the internal IpOpt headers are not installed by simbody. 

cc @scpeters @j-rivero @aerydna @drdanz

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR fixes #510 by changing the `Ipopt` namespace to `SimTKIpopt`. This allows me to use Simbody with a different Ipopt in my direct collocation software.

An alternative solution is to create an option for users to "bring their own Ipopt" for use by Simbody. Changing the namespace is a quicker fix and prevents "branching" where Simbody is packaged differently on different platforms, etc. Also, Simbody's Optimizer classes provide dense Jacobian and Hessian matrices and Simbody's Ipopt uses a dense linear solver. I'm not sure that the sparse solvers that Ipopt typically uses would perform as well with dense matrices.

I'm not sure what the license implications are of my changes to Ipopt. If preferred, I could create a patch file and have CMake apply a patch to these files, rather than modifying them directly. Not sure if that helps (FYI this license file in the repo may be helpful for thinking about this: https://github.com/simbody/simbody/blob/master/SimTKmath/Optimizers/src/IpOpt/LICENSE.txt).

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/580)

### CODE REVIEW

**Comment by chrisdembia** [comment]
I expect that the `travis-ci/push` build will fail, but the `travis-ci/pr` build should pass (because it incorporates the recently merged PR), and so I think we can ignore the `travis-ci/push` failure.

**Comment by sherm1** [comment]
@chrisdembia I don't think there are any license implications. We have already made many small changes to the embedded IpOpt.

**Comment by chrisdembia** [comment]
> @chrisdembia I don't think there are any license implications. We have already made many small changes to the embedded IpOpt.

Okay then I think this might be ready to be merged.

**Comment by chrisdembia** [comment]
Thanks @sherm1

**Pull request merged**
