### PR TITLE
Move doxygen files to doc/

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR moves the doxygen input files from the root of the repository to the `doc/` folder. This has the benefit of cleaning up the root directory. I'm making this PR in advance of creating a new Doxygen page for ADOLC-related information.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/595)

### CODE REVIEW

**Comment by sherm1** [comment]
A few comments, ptal ...

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 632 at r1](https://reviewable.io:443/reviews/simbody/simbody/595#-L1YOKs0xkw0Y3nbCRJl:-L1YOKs0xkw0Y3nbCRJm:b-jg40yw) ([raw file](https://github.com/simbody/simbody/blob/1c86c3d7374769801bc76c6b3d47c419f2cfb4bb/CMakeLists.txt#L632)):*
> ```CMake
> endif()
> 
> file(GLOB TOPLEVEL_DOCS LICENSE.txt *.md doc/*.pdf doc/*.md)
> ```

BTW why remove `doc/*.txt`?

---

*[doc/Doxyfile.in, line 813 at r1](https://reviewable.io:443/reviews/simbody/simbody/595#-L1YPPUMKdnT1BSE07rN:-L1YPPUMKdnT1BSE07rO:by8mir7) ([raw file](https://github.com/simbody/simbody/blob/1c86c3d7374769801bc76c6b3d47c419f2cfb4bb/doc/Doxyfile.in#L813)):*
> ```
>                          *.in \
>                          */Platform/* \
>                          */cmake/* \
> ```

BTW Is removing `*/doc/*` so you can put a header or source file in a doc directory? That also means all the lower-level doc directories will get visited by Doxygen. If you plan to add a doxygen-only header, have you considered instead adding it in an ordinary include directory, maybe with a distinctive name like `adolc_doxygen.h`? Then it doesn't have to be treated differently from the other places we have doxygen gather its documentation. Not sure which is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/595#-:-L1YQJxXC4I63seexpPy:b-ql1f0v)*

**Comment by chrisdembia** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 632 at r1](https://reviewable.io:443/reviews/simbody/simbody/595#-L1YOKs0xkw0Y3nbCRJl:-L1_FZGwb0ZYLlCdx3dX:bp6540t) ([raw file](https://github.com/simbody/simbody/blob/1c86c3d7374769801bc76c6b3d47c419f2cfb4bb/CMakeLists.txt#L632)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW why remove `doc/*.txt`?
</blockquote></details>

There is now a `CMakeLists.txt` in `doc/` that we do not want to install. There are no other .txt files in `doc/`.

---

*[doc/Doxyfile.in, line 813 at r1](https://reviewable.io:443/reviews/simbody/simbody/595#-L1YPPUMKdnT1BSE07rN:-L1_FhnyQDDVlrzjoAYE:bdtmgfu) ([raw file](https://github.com/simbody/simbody/blob/1c86c3d7374769801bc76c6b3d47c419f2cfb4bb/doc/Doxyfile.in#L813)):*
> Is removing */doc/* so you can put a header or source file in a doc directory?

Yes.

I've reverted this change and moved `SimbodyMainpage.h` back to the root of the repository. The `adolc_doxygen` branch (based on this branch) now places a `SimbodyDoxygenADOLC.h` file in the root of the repository.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/595)*

**Comment by chrisdembia** [comment]
Thanks for the comments. Ready for review again.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/595#-:-L1_G-RGPU6C0QuzMCTT:b-bq70zg)*

**Comment by chrisdembia** [comment]
@antoinefalisse note that I've updated the `adolc_doxygen` branch based on my changes in this PR.

**Comment by antoinefalisse** [comment]
@chrisdembia, good to know thanks.

**Comment by sherm1** [comment]
+@sherm1 
:lgtm:

---

Reviewed 1 of 9 files at r1, 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/595#-:-L2HRGuMWkGaVRO3rn3-:bthp7bq)*

**Comment by chrisdembia** [comment]
Thanks @sherm1

**Pull request merged**
