### PR TITLE
Replace pthreads

### PR DESCRIPTION
**Pull request by chrisdembia**
See #584

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/602)

### CODE REVIEW

**Comment by sherm1** [comment]
Checkpoint: the easy stuff!

---

Reviewed 15 of 24 files at r1.
Review status: 15 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[SimTKcommon/Random/src/Random.cpp, line 32 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Ye6SYJlyuo8EbEuR7:-L1Ye6SYJlyuo8EbEuR8:bgn4sfh) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/Random/src/Random.cpp#L32)):*
> ```cpp
> #include <cassert>
> #include <cmath>
> #include <atomic>
> ```

BTW redundant

---

*[SimTKmath/Geometry/src/ContactGeometryImpl.h, line 37 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YctShOlCopJSjbJJ8:-L1YctShOlCopJSjbJJ9:bgn4sfh) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKmath/Geometry/src/ContactGeometryImpl.h#L37)):*
> ```objc
> #include <atomic>
> #include <limits>
> #include <atomic>
> ```

BTW redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1YeNI7AVkhL6ftRrvP:bsvqa3t)*

**Comment by sherm1** [comment]
Checkpoint: all but visualizer!

---

Reviewed 4 of 24 files at r1.
Review status: 19 of 24 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 89 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YqmwY4L-mZ2zERJC2:-L1YqmwY4L-mZ2zERJC3:bl8dvch) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L89)):*
> ```cpp
>     {
>       threads.resize(numMaxThreads);
>       for (int i = 0; i < numMaxThreads; ++i) {
> ```

BTW per @chrisdembia: consider whether this should be `i=threads.size()` rather than `i=0`? (What happens if not all the threads get created in a single call?)

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 90 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yr53wVdDPWMyfShfr:-L1Yr53wVdDPWMyfShfs:btyaqk3) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L90)):*
> ```cpp
>       threads.resize(numMaxThreads);
>       for (int i = 0; i < numMaxThreads; ++i) {
>           threadInfo.push_back(new ThreadInfo(i, this));
> ```

BTW there is a raw pointer here -- who owns this object? Better to use: (1) plain old stack variable if possible, otherwise (2) a unique_ptr to make ownership clear, or (3) a shared_ptr if that is really, really necessary!

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 124 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yq0ReivBp843dL2i6:-L1Yq0ReivBp843dL2i7:b13vhut) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L124)):*
> ```cpp
>  */
> 
> void threadBody(ThreadInfo* info) {
> ```

BTW could just be a reference to something owned elsewhere? 

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 161 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YpezD-aKhzmgbtV9Q:-L1YpezD-aKhzmgbtV9R:bbpt9p4) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L161)):*
> ```cpp
>         }
>     }
>     delete info;
> ```

BTW seems odd to delete this here without having transferred ownership. However, ok to leave it if you don't want to clean this up now.

---

*[SimTKcommon/src/ParallelExecutorImpl.h, line 91 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yrfe6f1WmaDXyjGmW:-L1Yrfe6f1WmaDXyjGmX:brittro) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutorImpl.h#L91)):*
> ```objc
>     std::condition_variable runCondition, waitCondition;
>     Array_<std::thread> threads;
>     Array_<ThreadInfo*> threadInfo;
> ```

BTW who owns the objects pointed to in threadInfo?

---

*[SimTKcommon/src/ParallelWorkQueue.cpp, line 94 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YzA0y9Wkb1VqIfm0o:-L1YzA0y9Wkb1VqIfm0p:bm2j6ol) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelWorkQueue.cpp#L94)):*
> ```cpp
>     taskQueue.push(task);
>     ++pendingTasks;
>     waitForTaskCondition.notify_one();
> ```

BTW for consistency, consider explicitly unlocking or at least a comment noting that it is happening. Or -- don't explicitly unlock and end-of-scope elsewhere?

---

*[SimTKcommon/src/ParallelWorkQueue.cpp, line 100 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YzZwLyI9PnQGiBZBA:-L1YzZwLyI9PnQGiBZBB:bxa0o7j) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelWorkQueue.cpp#L100)):*
> ```cpp
>     std::unique_lock<std::mutex> lock(queueMutex);
>     queueFullCondition.wait(lock, [this] { return pendingTasks == 0; });
> }
> ```

BTW explicit unlock?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1Yzi2oDWb7AVJcBOjt:bmn4i7m)*

**Comment by sherm1** [comment]
Review pass complete. Looks great pending timed select() stuff if you decide to do that. And some miscellaneous minor stuff ...

---

Reviewed 5 of 24 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[Simbody/Visualizer/src/Visualizer.cpp, line 358 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZjuvDNxM3_EPJzWVE:-L1ZjuvDNxM3_EPJzWVF:b-wijny4) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/Visualizer.cpp#L358)):*
> ```cpp
>             return;
>         std::unique_lock<std::mutex> lock(m_queueMutex);
>         m_queueIsEmpty.wait(lock, [&] {return m_nframe == 0;});
> ```

BTW consider an unlock comment or explicit unlock

---

*[Simbody/Visualizer/src/Visualizer.cpp, line 400 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZkBVanroT0czkBhip:-L1ZkBVanroT0czkBhiq:b-ud00hx) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/Visualizer.cpp#L400)):*
> ```cpp
>         if (m_nframe <= m_pool.size()/2+1)
>             m_queueNotFull.notify_one();
>     }
> ```

BTW unlock?

---

*[Simbody/Visualizer/src/Visualizer_InputListener.cpp, line 46 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZixIVZOMJqBh0gw28:-L1ZixIVZOMJqBh0gw29:b-wxh4v7) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/Visualizer_InputListener.cpp#L46)):*
> ```cpp
> public:
>     using Lock = std::unique_lock<std::mutex>;
>     Lock LOCK_silo()     const {return Lock(m_siloMutex);}
> ```

BTW consider whether it would be better to do away with all these helpers and just expose the mutexes and the std::lock stuff where it is being used.

---

*[Simbody/Visualizer/src/VisualizerProtocol.cpp, line 176 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Zg5FHDueaU1RKHWVC:-L1Zg5FHDueaU1RKHWVD:bp61lnv) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/VisualizerProtocol.cpp#L176)):*
> ```cpp
>     int totalRead = 0;
>     while (totalRead < bytes) {
>         auto retval = READ(srcPipe, buffer + totalRead, bytes - totalRead);
> ```

BTW per f2f: use select() with timeout?

---

*[Simbody/Visualizer/src/VisualizerProtocol.cpp, line 434 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZKkBgoy_5MA6I89GJ:-L1ZKkBgoy_5MA6I89GK:bhxlfzm) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/VisualizerProtocol.cpp#L434)):*
> ```cpp
> 
> void VisualizerProtocol::beginScene(Real time) {
>     sceneLockBeginEnd = std::unique_lock<std::mutex>(sceneMutex);
> ```

BTW per f2f discussion: better if this were just `sceneLockBeginEnd.lock()`.

---

*[Simbody/Visualizer/src/VisualizerProtocol.h, line 167 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZKxHQDfxaMsNoWMCF:-L1ZKxHR0gsoqNEnz4So:b-q51dyg) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/VisualizerProtocol.h#L167)):*
> ```objc
>     mutable std::mutex sceneMutex;
>     // This lock should only be used in beginScene() and endScene().
>     std::unique_lock<std::mutex> sceneLockBeginEnd;
> ```

BTW consider making this `sceneLockBeginEnd{scendMutex, std::defer_lock}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1ZkKgo1eq1x4a1gYY5:b-a0f316)*

**Comment by chrisdembia** [comment]
Review status: 1 of 9 files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[Simbody/Visualizer/src/Visualizer.cpp, line 358 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZjuvDNxM3_EPJzWVE:-L1iOaUTn7EO8QBqp2BR:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/Visualizer.cpp#L358)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider an unlock comment or explicit unlock
</blockquote></details>

Done.

---

*[Simbody/Visualizer/src/Visualizer.cpp, line 400 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZkBVanroT0czkBhip:-L1iObvYu4BWzFWch3du:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/Visualizer.cpp#L400)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW unlock?
</blockquote></details>

Done.

---

*[Simbody/Visualizer/src/Visualizer_InputListener.cpp, line 46 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZixIVZOMJqBh0gw28:-L1iOcpjcnbaVU_6vS3u:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/Visualizer_InputListener.cpp#L46)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider whether it would be better to do away with all these helpers and just expose the mutexes and the std::lock stuff where it is being used.
</blockquote></details>

Done.

---

*[Simbody/Visualizer/src/VisualizerProtocol.cpp, line 176 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Zg5FHDueaU1RKHWVC:-L1iP2AjtR2-zW2XbwK1:b-6wqdtr) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/VisualizerProtocol.cpp#L176)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f: use select() with timeout?
</blockquote></details>

I tried this and it worked on Mac/Linux. I had trouble on Windows. Plus, on Windows, this requires linking to the Windows Sockets 2 library, which could cause a mess.

So I'm trying an alternate approach: when the simulator wants to stop listening, the simulator sends a message to the GUI to close the viz2sim pipe. I'm about halfway done with this implementation and it seems cleaner.

---

*[Simbody/Visualizer/src/VisualizerProtocol.cpp, line 434 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZKkBgoy_5MA6I89GJ:-L1iOi6LfNIGVr-MqQ7q:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/VisualizerProtocol.cpp#L434)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per f2f discussion: better if this were just `sceneLockBeginEnd.lock()`.
</blockquote></details>

Done.

---

*[Simbody/Visualizer/src/VisualizerProtocol.h, line 167 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ZKxHQDfxaMsNoWMCF:-L1iOjdZi3gcNySPdrv2:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/Simbody/Visualizer/src/VisualizerProtocol.h#L167)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider making this `sceneLockBeginEnd{scendMutex, std::defer_lock}`
</blockquote></details>

Done.

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 89 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YqmwY4L-mZ2zERJC2:-L1iOm9nsakjoxNwu_D0:bz1ymn9) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L89)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW per @chrisdembia: consider whether this should be `i=threads.size()` rather than `i=0`? (What happens if not all the threads get created in a single call?)
</blockquote></details>

I added a comment and an assert() that should address this concern.

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 90 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yr53wVdDPWMyfShfr:-L1ckCzAFbnp0dsKmTj8:beiiix0) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L90)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW there is a raw pointer here -- who owns this object? Better to use: (1) plain old stack variable if possible, otherwise (2) a unique_ptr to make ownership clear, or (3) a shared_ptr if that is really, really necessary!
</blockquote></details>

I was able to do (1) and that works on Mac but not on Windows for some reason. I need to keep debugging.

Maybe when you first tried this, we were missing the required `std::ref()` in the next line?

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 124 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yq0ReivBp843dL2i6:-L1ckEQ1AliXAskaUqDQ:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L124)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW could just be a reference to something owned elsewhere? 
</blockquote></details>

Done.

---

*[SimTKcommon/src/ParallelExecutor.cpp, line 161 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YpezD-aKhzmgbtV9Q:-L1ck-O2eKiV_j61xWPl:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutor.cpp#L161)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW seems odd to delete this here without having transferred ownership. However, ok to leave it if you don't want to clean this up now.
</blockquote></details>

Done.

---

*[SimTKcommon/src/ParallelExecutorImpl.h, line 91 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yrfe6f1WmaDXyjGmW:-L1cjyhMOU4Os6Bg-Gc5:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutorImpl.h#L91)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW who owns the objects pointed to in threadInfo?
</blockquote></details>

Done.

---

*[SimTKcommon/src/ParallelWorkQueue.cpp, line 94 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YzA0y9Wkb1VqIfm0o:-L1iP-T8gmL-EzmLVPMy:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelWorkQueue.cpp#L94)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW for consistency, consider explicitly unlocking or at least a comment noting that it is happening. Or -- don't explicitly unlock and end-of-scope elsewhere?
</blockquote></details>

Done.

---

*[SimTKcommon/src/ParallelWorkQueue.cpp, line 100 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YzZwLyI9PnQGiBZBA:-L1iOzqOsMi_v7iMbC1b:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelWorkQueue.cpp#L100)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW explicit unlock?
</blockquote></details>

Done.

---

*[SimTKcommon/Random/src/Random.cpp, line 32 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Ye6SYJlyuo8EbEuR7:-L1ck3Tj-2eN0vJpXG1W:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/Random/src/Random.cpp#L32)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW redundant
</blockquote></details>

Done.

---

*[SimTKmath/Geometry/src/ContactGeometryImpl.h, line 37 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1YctShOlCopJSjbJJ8:-L1ck53PtDe9az3UzL7v:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKmath/Geometry/src/ContactGeometryImpl.h#L37)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW redundant
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602)*

**Comment by chrisdembia** [comment]
@sherm1 I've made most of the minor changes and I am still working on the bug with closing the pipes. Not quite ready for review yet.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1iQ4MwSerlycewhoX-:b-b6zdej)*

**Comment by chrisdembia** [comment]
This PR is ready for review.

I've redone how the listener thread dies, and the simulator no longer hangs and there is no error message anymore when closing the GUI after the simulation is done (on both Linux and Windows).

Here are the scenarios I've tested on Mac, Linux, and Windows, for ExamplePendulum and/or TaskSpaceControl-UR10:

- Interacting with sliders and key presses (to toggle target tracking, etc.).
- After the simulator terminates successfully, I can still use the GUI by rotating the view, moving sliders (though they have no effect), and choosing menu options (most of which do have an effect, like changing the background).
- After the simulator terminates successfully, closing the GUI by hitting a key. This works as expected (not all keys will cause the GUI to shut down though; modifiers like Shift won't have an effect).
- While the simulator is running, closing the GUI using the X button in the title bar (or Cmd+Q on Mac). On Mac, the simulator terminated without any error message, but on Ubuntu I got a "Broken pipe" error message from the simulator and on Windows I get some other type of fatal error. I think this is reasonable behavior; the user killed the GUI while the simulator was still trying to communicate with it.
- Terminating the simulator before the simulation is done (Ctrl+C in the terminal). On both Mac and Linux, this causes the GUI to shut down without any error messages. I did not test this on Windows.

---

Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1kOro7D7Liu0-BfF5A:bo2ogns)*

**Comment by sherm1** [comment]
*[Simbody/Visualizer/src/Visualizer_InputListener.cpp, line 99 at r2](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ou7nd4aPC229Jgi_U:-L1ou7nd4aPC229Jgi_V:bw5r31o) ([raw file](https://github.com/simbody/simbody/blob/2548e80961849ef148af6a9d09f11698d032a44c/Simbody/Visualizer/src/Visualizer_InputListener.cpp#L99)):*
> ```cpp
>     Impl& impl = updImpl();
>     std::unique_lock<std::mutex> lock(impl.m_siloMutex);
>     impl.m_keyHitAvailable.wait(lock, [&] {return impl.m_keyHitSilo.size();});
> ```

BTW this surprised me a little because the lambda returns a size_t rather than a book and I thought wait() would want something with signature `bool Pred()`. But apparently any function that can be interpreted as a bool is acceptable. And it does seem cleaner like this. No change suggested -- just a side comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602)*

**Comment by sherm1** [comment]
I tried the new version on Windows and it seemed to work fine, including CtrlC'ing the simulator early. This all looks great to me -- a few minor comments below, PTAL. :lgtm_strong:

---

Reviewed 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Simbody/Visualizer/src/Visualizer_InputListener.cpp, line 184 at r2](https://reviewable.io:443/reviews/simbody/simbody/602#-L1oup5OauMv2HOXJeNg:-L1oup5OauMv2HOXJeNh:boyxkbt) ([raw file](https://github.com/simbody/simbody/blob/2548e80961849ef148af6a9d09f11698d032a44c/Simbody/Visualizer/src/Visualizer_InputListener.cpp#L184)):*
> ```cpp
>     if (impl.m_keyHitSilo.size() == 1)
>         // a key hit is now available
>         impl.m_keyHitAvailable.notify_one();
> ```

BTW a multi-line `if` should have braces, even though this will work properly due to one of the lines being just a comment. That's hard for a human to grasp and could easily lead to future errors or current misunderstandings. (Here and just above and below.)

---

*[Simbody/Visualizer/src/VisualizerProtocol.cpp, line 419 at r2](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ovgVXcPjJnmIuoeMz:-L1ovgVXcPjJnmIuoeN-:bx4gy7f) ([raw file](https://github.com/simbody/simbody/blob/2548e80961849ef148af6a9d09f11698d032a44c/Simbody/Visualizer/src/VisualizerProtocol.cpp#L419)):*
> ```cpp
>     // running and we should kill it.
>     stopListeningIfNecessary();
>     int retval = CLOSE(outPipe); // TODO is this necessary?
> ```

BTW suggestion -- we've been following the Google convention for TODOs which is to always put the TODO-author's GitHub name in parens so future programmers know who added it and who to ask about. Like: `// TODO(chrisdembia) is this necessary?`. I've come to like that convention.

---

*[SimTKcommon/src/ParallelExecutorImpl.h, line 91 at r1](https://reviewable.io:443/reviews/simbody/simbody/602#-L1Yrfe6f1WmaDXyjGmW:-L1ox5CHi18Ffe65JKQr:b-y87etv) ([raw file](https://github.com/simbody/simbody/blob/f87d33ef4fcff2d7f2983206ef12441fe134f3bc/SimTKcommon/src/ParallelExecutorImpl.h#L91)):*
<details><summary><i>Previously, chrisdembia (Christopher Dembia) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is a nice improvement -- thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1osPgpxr6OfnJY8M6A:bsbrrnz)*

**Comment by sherm1** [comment]
+@sherm1

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1oxe8ptjw9w83El31A:b-1y6uu8)*

**Comment by chrisdembia** [comment]
@sherm1 I've attempted to address your comments. I also deleted the pthreads files and ensured that the text "pthread" only appears in the repo in comments describing our previous use of pthreads. Please review the changes in common.h. Ready for review.

---

Review status: 7 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[Simbody/Visualizer/src/Visualizer_InputListener.cpp, line 184 at r2](https://reviewable.io:443/reviews/simbody/simbody/602#-L1oup5OauMv2HOXJeNg:-L1pA80l4UxGN05C61yi:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/2548e80961849ef148af6a9d09f11698d032a44c/Simbody/Visualizer/src/Visualizer_InputListener.cpp#L184)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW a multi-line `if` should have braces, even though this will work properly due to one of the lines being just a comment. That's hard for a human to grasp and could easily lead to future errors or current misunderstandings. (Here and just above and below.)
</blockquote></details>

Done.

---

*[Simbody/Visualizer/src/VisualizerProtocol.cpp, line 419 at r2](https://reviewable.io:443/reviews/simbody/simbody/602#-L1ovgVXcPjJnmIuoeMz:-L1pA1Glwed_2NedPcvV:bd4d6si) ([raw file](https://github.com/simbody/simbody/blob/2548e80961849ef148af6a9d09f11698d032a44c/Simbody/Visualizer/src/VisualizerProtocol.cpp#L419)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW suggestion -- we've been following the Google convention for TODOs which is to always put the TODO-author's GitHub name in parens so future programmers know who added it and who to ask about. Like: `// TODO(chrisdembia) is this necessary?`. I've come to like that convention.
</blockquote></details>

I like it; I edited this comment to use that convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L1pAP51hpbvs0Zs2Byi:b-oc1zq1)*

**Comment by sherm1** [comment]
So nice to see the last of all that pthreads cruft! Thanks, @chrisdembia.

---

Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/602#-:-L2HQ4LiP-PLSLe9fMls:bytmrmq)*

**Comment by chrisdembia** [comment]
Woohoo! Thanks @sherm1

**Pull request merged**
