### PR TITLE
Whitespace

### PR DESCRIPTION
**Pull request by thomasklau**

### CODE REVIEW

**Comment by thomasklau** [comment]
@sherm1

**Comment by thomasklau** [comment]
Separate pull request so that I can submit my other pull request without whitespace changes

**Comment by thomasklau** [comment]
https://github.com/simbody/simbody/pull/412

**Comment by chrisdembia** [comment]
Hey @thomasklau; this PR makes changes to binary files. Are you sure that is okay? I think those files shouldn't be modified for whitespace.

**Comment by sherm1** [comment]
Hi, Thomas. There is something wrong with this PR. It says it changed 887 files, but many of those have 0 changes. GitHub also says it can't be merged automatically. Possibly something messed with the line ending characters?

Please discuss with @chrisdembia. You may want to give up on fixing up whitespace. Although it is nice, it is not critical and is interfering with your important work!

**Comment by sherm1** [comment]
> this PR makes changes to binary files. Are you sure that is okay? 

Definitely not! I would like to see changes that only involve the new parallel execution code. Let's forget about whitespace fixup for now.

**Comment by chrisdembia** [comment]
@thomasklau you could use git-cherry-pick to apply your parallel execution code to a new branch that does not contain the whitespace changes.

**Comment by thomasklau** [comment]
Okay, I'll try doing that - sorry for the delay.

**Pull request closed without merging**
