### PR TITLE
Added Dzhanibekov Effect example

### PR DESCRIPTION
**Pull request by sherm1**
The Dzhanibekov Effect is a non-intuitive rigid body effect in which a smoothly rotating rigid body suddenly flips 180 degrees, then rotates smoothly, then flips again, etc. It is best seen in zero gravity: compare [this one on the space station](https://youtu.be/L2o9eBl_Gzw) with [this one in Simbody](https://youtu.be/L8B83DUKiiA) produced using this example.
 
Erwin Coumans posted a simulation in Bullet [here](https://plus.google.com/+erwincoumans/posts/TAyj5x4Q1HQ), which inspired me to try it in Simbody.

Here is another real-life [space station video](https://youtu.be/JB0OAt4zQ1E?t=29s) (in Russian but it doesn't matter).

### CODE REVIEW

**Comment by tkuchida** [comment]
:+1: :-1: :+1: :-1: :+1:

**Comment by sherm1** [comment]
The GitHub `:-1:` isn't displaying for me :cry:. But `:thumbsdown:` worked:
:+1::thumbsdown::+1::thumbsdown::+1:

You must be a rigid body with unequal inertias!

**Comment by sherm1** [comment]
Now the `:-1:`s are working too :confused:.

**Comment by tkuchida** [comment]
They ǝɹɐ all sqɯnɥʇ ups! :smile:

**Comment by sherm1** [comment]
Wait ... what? How do you make upside-down text?

**Comment by sherm1** [comment]
¡ʍou ʇı ʇǝƃ ı 'ɥo

**Comment by tkuchida** [comment]
Nice timing. I was just about to hit you with [this](http://lmgtfy.com/?q=type+upside+down) :smile:

**Comment by sherm1** [comment]
Yeah, I had that thought right after I asked that dumb question!

**Comment by sherm1** [comment]
Anyway, since you sent so many thumbs up, and Travis and AppVeyor agree with you, I'm merging this example.

**Comment by tkuchida** [comment]
This would make a nice example for the verification and validation talk!

**Comment by sherm1** [comment]
Check it out, @erwincoumans! (See links in PR description)

**Comment by scpeters** [comment]
I added a [gazebo test](https://bitbucket.org/osrf/gazebo/pull-request/1482/add-link-getworldangularmomentum-enable/diff#Ltest/integration/physics_link.ccT92) that captures this effect, though I didn't know this name for that effect. I guess I need to make it easier to visualize the gazebo tests, which mostly run headless.

**Comment by scpeters** [comment]
Is there an easy way to print out the inertia matrix for the rigid body in this test? I'm sure there is actually, but I don't know the simbody API as well as you.

**Comment by chrisdembia** [comment]
Does this work?https://simtk.org/api_docs/simbody/latest/singletonSimTK_1_1Inertia__.html#a8cb59637de516910c73d319d793f53db

**Comment by scpeters** [comment]
Well it's a `MultibodySystem` with two rigid bodies welded together, so I would need to figure out where the c.g. is located, then compute the lumped moment of inertia at that point. So I guess the hard part isn't printing out the inertia matrix, but rather computing it from the `MultibodySystem`.

**Comment by sherm1** [comment]
There is no unique frame in which to express the inertia, since each of the bodies has its own frame. You could ask for it in the ground (world) frame but then you have to have a State so you can find out how the bodies are positioned in space. Probably better to pick one of the bodies as the "main" body and then rotate and shift the other inertia into that frame. What do you have in mind?

**Comment by sherm1** [comment]
Here's a possibility. If you know that the two welded-together bodies are the only ones in the MultibodySystem, then the inertia you are interested in is the central system inertia (meaning system inertia taken about the system COM). There's an API for that:
```c++
    system.realize(state, Stage::Position);
    Inertia sysInertia = matter.calcSystemCentralInertiaInGround(state);
    std::cout << "System Inertia in Ground = " << sysInertia;
    std::cout << "System COM location = " 
        << matter.calcSystemMassCenterLocationInGround(state) << std::endl;
```
where "matter" is the SimbodyMatterSubsystem contained in the system. This inertia is expressed in Ground though, so it will look different in different orientations. To keep it constant you would need to re-express it in some frame fixed to one of the bodies.

**Comment by scpeters** [comment]
I just wanted to see what the inertia matrix would be for this system if it was modeled as a single rigid body instead of two bodies welded together, since the "[Tennis Racket Theorem](http://en.wikipedia.org/wiki/Tennis_racket_theorem)" says that the rotational stability of a single rigid body about each principal axis depends on the relative moment of inertia about each axis. See also the comments in the [gazebo test](https://bitbucket.org/osrf/gazebo/pull-request/1482/add-link-getworldangularmomentum-enable/diff#Ltest/integration/physics_link.ccT92).

I could compute this by hand using the parallel axis theorem, but I was trying to be lazy.

**Comment by sherm1** [comment]
I understand. But since there are two bodies with two different body frames, you have to decide on a frame in which to express the inertia. If their frames are aligned then it doesn't matter; it isn't clear to me whether that is the case here. Simbody has "shift" methods on Inertia, UnitInertia, and MassProperties classes that will take care of parallel axis stuff for you.

**Comment by scpeters** [comment]
The "central system inertia" sounds like what I want, and since I only care about the principal inertia values, I would take that matrix in any frame (such as the Ground frame) and then compute the eigenvalues.

**Comment by sherm1** [comment]
The system central inertia code I posted gave this as output for Simbody's test case with all the state variables set to zero (the way I built it puts the center of the red shaft at Ground 0,0,0):
image
```
System Inertia in Ground =
[0.0612667,0,0]
[0,0.0644667,0]
[0,0,0.00553333]
System COM location = ~[-0.0466667,0,0]
```

**Comment by erwincoumans** [comment]
In Bullet you can compute the same using void btCompoundShape::calculatePrincipalAxisTransform and pass in the inertias/masses/transforms of each component.

**Comment by scpeters** [comment]
That makes sense then. In this model, `Izz` < `Ixx` < `Iyy`, and the `X` axis is the unstable one.

@erwincoumans that's true, I see that's part of the GyroscopicSetup.cpp file.

**Pull request merged**
