### PR TITLE
[appveyor] Disable publishing to AppVeyor's NuGet feed from pull requests

### PR DESCRIPTION
**Pull request by chrisdembia**
AppVeyor lets us upload Simbody binaries to AppVeyor's servers, using our NuGet "feed" provided by AppVeyor. As-is, strangers can open PRs on Simbody to push arbitrary things to our NuGet feed. This PR prevents that.

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/578)

### CODE REVIEW

**Comment by sherm1** [comment]
Has some CI failures on Travis.

**Comment by chrisdembia** [comment]
I fixed the Travis CI failures.

**Comment by chrisdembia** [comment]
@sherm1 This is ready for review again.

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/578#-:-L3tH3Yw42_XBIZ7EStC:bnfp4nl)*

**Pull request merged**
