### PR TITLE
Update README and documentation for 3.6.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR updates the README and user guide, etc. for the 3.6 release. The only changes I made to the docx and pdf files were updating the version number from 3.5 to 3.6 and changing the date to January, 2018; both changes are on the title page.

+@sherm1

---
This change is [Reviewable](https://reviewable.io/reviews/simbody/simbody/612)

### CODE REVIEW

**Comment by chrisdembia** [comment]
This PR predicts the release date of 3.6 to be 13 January 2018.

**Comment by sherm1** [comment]
:lgtm: -- thanks, Chris. One addition to the change log.

---

Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 90 at r1](https://reviewable.io:443/reviews/simbody/simbody/612#-L2lyyEtYqGU40lU1SFH:-L2lyyEtYqGU40lU1SFI:b-534xyl) ([raw file](https://github.com/simbody/simbody/blob/63839a3f6b901bb679d33b6360ed713a49cc5a85/CHANGELOG.md#L90)):*
> ```Markdown
> * Removed support for `long double`. 
>   [PR #597](https://github.com/simbody/simbody/pull/597)
> * Moved Ipopt into the namespace `SimTKIpopt` to avoid duplicate symbols when
> ```

BTW one I forgot:
```
* Fixed a bug in MultibodyGraphMaker where massless bodies 
were handled incorrectly.
[PR #592](https://github.com/simbody/simbody/pull/592) and 
[PR #594](https://github.com/simbody/simbody/pull/594).
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/612#-:-L2m-BkaFh8sa9j6-Hx0:btsup9x)*

**Comment by chrisdembia** [comment]
I incorporated your addition to the change log. 

I updated the links for the doxygen in README.md and the user manual to use a github-based URL rather than the SimTK URL.

I also updated the license section of the user guide, which previously contained (ignore highlighting):



This section is now as shown:


Ready for review again.

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 90 at r1](https://reviewable.io:443/reviews/simbody/simbody/612#-L2lyyEtYqGU40lU1SFH:-L2m7TAglI6P77hPOO8v:b-896fix) ([raw file](https://github.com/simbody/simbody/blob/63839a3f6b901bb679d33b6360ed713a49cc5a85/CHANGELOG.md#L90)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW one I forgot:
```
* Fixed a bug in MultibodyGraphMaker where massless bodies 
were handled incorrectly.
[PR #592](https://github.com/simbody/simbody/pull/592) and 
[PR #594](https://github.com/simbody/simbody/pull/594).
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/612#-:-L2mDsY73VpBgrHMYQTk:b-2acsty)*

**Comment by sherm1** [comment]
Great -- thanks! Ready to merge.

---

Reviewed 2 of 4 files at r2.
Review status: 2 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/612#-:-L2mHia6QFxqhSswq_KR:b-l0dl0y)*

**Comment by sherm1** [comment]
Reviewed 4 of 8 files at r1, 2 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/simbody/simbody/612)*

**Pull request merged**
