### PR TITLE
Fix for issue #350

### PR DESCRIPTION
**Pull request by nishbo**
For main and one other make files

(also removed trailing whitespace)

### CODE REVIEW

**Comment by scpeters** [comment]
[diff without whitespace changes](https://github.com/simbody/simbody/pull/352/files?w=1)

**Comment by nishbo** [comment]
@scpeters, should I redo it?

**Comment by scpeters** [comment]
No, I was just giving a link to make it easier to review the non-whitespace changes. I'll let @sherm1 decide if the whitespace removal is ok.

**Comment by sherm1** [comment]
> I'll let @sherm1 decide if the whitespace removal is ok.

Definitely! I don't like those junky blanks there either -- thanks, Anton.

**Comment by chrisdembia** [comment]
@nishbo did you test locally using g++ on OSX? Good catch on editing the InstalledCMakeLists.txt. If so, this looks good to me.

**Comment by scpeters** [comment]
I haven't tested it, but if I did, I would try `brew install gcc` to get `g++`

**Comment by chrisdembia** [comment]
@sherm1 I think we should merge this.

**Comment by sherm1** [comment]
Oh I forgot about this one. Thanks, Chris. And thanks for the PR @nishbo.

**Pull request merged**
