### PR TITLE
[static] Allow only static compilation of simbody

### PR DESCRIPTION
**Pull request by Gjacquenot**
This PR adds the possibility to compile simbody in a all static way

We use it with 

    cmake -DBUILD_DYNAMIC_LIBRARIES:BOOL=OFF -DBUILD_STATIC_LIBRARIES:BOOL=ON ....

A message error is thrown in case these two options are set to `FALSE`...

Reason of this PR:

When needing only static version, we can avoid dynamic compilation (save 50% compilation time). Also  dynamic compilation requires to have blas/lapack to be compiled with -fPIC in case of use of static version.
Disabling dynamic compilation allows to use static versions of blas/lapack coming from Linux distro, that do not use -fPIC for static libraries on 64 bit platform.

1) This PR does not change anything to the previous configuration and compilation steps for simbody

2) With static compilation, all tests do not succeed, because of tolerance problem

-  81 - GazeboReactionForceWithAppliedForceRigidStatic (Failed)
-  95 - GazeboReactionForceWithAppliedForceCompliantStatic (Failed)
- 104 - TestReverseMobilizersStatic (Failed)

One can see a log of these errors [here](https://travis-ci.org/Gjacquenot/simbody/jobs/256158634)

I have discussed this with @chrisdembia , who told me that this problem was known and already reported [here](https://github.com/simbody/simbody/issues/522).

3) Finally, I have fixed a broken mingw table in README.md.

### CODE REVIEW

**Comment by chrisdembia** [comment]
I think it would be nice to be able to build only the static libraries. I did a quick pass over the changes and they mostly look good. I can do an actual review in about a week.

**Comment by Gjacquenot** [comment]
Hi @chrisdembia , I have taken into account your remarks.

**Comment by Gjacquenot** [comment]
For time being, static versions of blas and lapack should be found by CMake using flag `BLA_STATIC` before `find_package`. Unfortunately, this CMake flag does not work, no library is found. When specifying manually the blas and lapack libraries a naive way, it leads to linking problem, like `multiple definition of `xerbla_'`. One needs something like `-Wl,--start-group $(LAPACK)/blas.a $(LAPACK)/lapack.a -Wl,--end-group`, plus libgfortran.a. I will post a Dockerfile, where one links statically againt lapack, blas and libgfortran, I already did it a long time ago...

**Comment by chrisdembia** [comment]
> @chrisdembia, did you get a chance to pull this and try the build?

No, good point. I'll try this out soon.

**Comment by sherm1** [comment]
Thanks!

**Comment by chrisdembia** [comment]
I just tested this locally on macOS and it worked great. The installation worked fine when setting `BUILD_DYNAMIC_LIBRARIES` to `OFF`. As expected, setting both `BUILD_DYNAMIC_LIBRARIES` and `BUILD_STATIC_LIBRARIES` to `OFF` caused CMake to generate an error message.

The only thing I noticed is that binary examples are only installed if dynamic libraries are built. I think this is fine, especially since the source code for the examples is always installed.

LGTM.

**Pull request merged**
